name = "TriangulArt"
uuid = "4e825928-4f37-4da1-b333-216cc9c54310"
authors = ["Jonathan Carroll"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
